disabled_rules:
- switch_case_alignment
- opening_brace # Forced to disable because this misunderstands some syntax that I use
- multiple_closures_with_trailing_closure

line_length: 150
type_body_length: 300
function_parameter_count: 8
file_length: 500
identifier_name:
  max_length: 60
function_body_length: 45
