name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
#       - name: Force Xcode 13
#         run: sudo xcode-select -switch /Applications/Xcode_13.0.app

      - name: Build
        run: swift build -c release --arch arm64 --arch x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: swift-bundler
          path: ./.build/apple/Products/Release/swift-bundler
