name: Build Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Swift version
        run: swift --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build
