name: Update Docs

on:
  push:
    branches: [ main ]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Swift version
        run: swift --version

      - uses: actions/checkout@v4

      - name: Compile Docs
        run: |
          set -eux
          git config user.email "stackotter@stackotter.dev"
          git config user.name "stackotter"
          git fetch
          git worktree add --checkout gh-pages origin/gh-pages
          export DOCC_JSON_PRETTYPRINT="YES"
          export SWIFTPM_ENABLE_COMMAND_PLUGINS=1 
          git clone https://github.com/stackotter/swift-docc-render-artifact ../swift-docc-render-artifact
          export DOCC_HTML_DIR=../swift-docc-render-artifact/dist
          swift package \
            --allow-writing-to-directory gh-pages/docs \
            generate-documentation \
            --target SwiftBundler \
            --disable-indexing \
            --transform-for-static-hosting \
            --output-path gh-pages/docs
          CURRENT_COMMIT_HASH=`git rev-parse --short HEAD`
          cd gh-pages
          # Inject our site at the index
          rm docs/index.html
          rm docs/favicon.ico
          cp index.html docs
          cp favicon.ico docs
          cp CNAME docs
          cp css/main.css docs/css
          cp -R image docs
          git add docs
          # Commit changes
          if [ -n "$(git status --porcelain)" ]; then
              echo "Documentation changes found. Commiting the changes to the 'gh-pages' branch and pushing to origin."
              git commit -m "Update GitHub Pages documentation site to '$CURRENT_COMMIT_HASH'."
              git push origin HEAD:gh-pages
          else
            echo "No documentation changes found."
          fi
